/*
 * generated by Xtext
 */
package org.ufacekit.qt.idl.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QIdlUiModule extends org.ufacekit.qt.idl.dsl.ui.AbstractQIdlUiModule {
	public QIdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
