/*
* generated by Xtext
*/
package org.ufacekit.qt.idl.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class QIdlOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
