/*
* generated by Xtext
*/
package org.ufacekit.qt.idl.dsl.ui.contentassist;

import org.ufacekit.qt.idl.dsl.ui.contentassist.AbstractQIdlProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class QIdlProposalProvider extends AbstractQIdlProposalProvider {

}
