/*
 * generated by Xtext
 */
package org.ufacekit.qt.idl.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QIdlRuntimeModule extends org.ufacekit.qt.idl.dsl.AbstractQIdlRuntimeModule {

}
