/*
* generated by Xtext
*/
package org.ufacekit.qt.idl.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.ufacekit.qt.idl.dsl.services.QIdlGrammarAccess;

public class QIdlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private QIdlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.ufacekit.qt.idl.dsl.parser.antlr.internal.InternalQIdlParser createParser(XtextTokenStream stream) {
		return new org.ufacekit.qt.idl.dsl.parser.antlr.internal.InternalQIdlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "QtIdlTyp";
	}
	
	public QIdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QIdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
