/*
* generated by Xtext
*/
package org.ufacekit.qt.idl.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QIdlAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/ufacekit/qt/idl/dsl/parser/antlr/internal/InternalQIdl.tokens");
	}
}
