/*
* generated by Xtext
*/
package org.ufacekit.qt.idl.dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.ufacekit.qt.idl.dsl.services.QIdlGrammarAccess;

public class QIdlParser extends AbstractContentAssistParser {
	
	@Inject
	private QIdlGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.ufacekit.qt.idl.dsl.ui.contentassist.antlr.internal.InternalQIdlParser createParser() {
		org.ufacekit.qt.idl.dsl.ui.contentassist.antlr.internal.InternalQIdlParser result = new org.ufacekit.qt.idl.dsl.ui.contentassist.antlr.internal.InternalQIdlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getQtIdlTypAccess().getElementAlternatives_0(), "rule__QtIdlTyp__ElementAlternatives_0");
					put(grammarAccess.getQtNamespaceAccess().getAlternatives_3(), "rule__QtNamespace__Alternatives_3");
					put(grammarAccess.getQtTypeAccess().getAlternatives(), "rule__QtType__Alternatives");
					put(grammarAccess.getQtOperationAccess().getAlternatives(), "rule__QtOperation__Alternatives");
					put(grammarAccess.getQtClassAccess().getAlternatives_5(), "rule__QtClass__Alternatives_5");
					put(grammarAccess.getQtEnumValueMaskAccess().getAlternatives_0(), "rule__QtEnumValueMask__Alternatives_0");
					put(grammarAccess.getQtEnumValueMaskAccess().getAlternatives_1_1(), "rule__QtEnumValueMask__Alternatives_1_1");
					put(grammarAccess.getQtParameterAccess().getAlternatives_1_1(), "rule__QtParameter__Alternatives_1_1");
					put(grammarAccess.getXAssignmentAccess().getAlternatives(), "rule__XAssignment__Alternatives");
					put(grammarAccess.getOpEqualityAccess().getAlternatives(), "rule__OpEquality__Alternatives");
					put(grammarAccess.getXRelationalExpressionAccess().getAlternatives_1(), "rule__XRelationalExpression__Alternatives_1");
					put(grammarAccess.getOpCompareAccess().getAlternatives(), "rule__OpCompare__Alternatives");
					put(grammarAccess.getOpOtherAccess().getAlternatives(), "rule__OpOther__Alternatives");
					put(grammarAccess.getOpAddAccess().getAlternatives(), "rule__OpAdd__Alternatives");
					put(grammarAccess.getOpMultiAccess().getAlternatives(), "rule__OpMulti__Alternatives");
					put(grammarAccess.getXUnaryOperationAccess().getAlternatives(), "rule__XUnaryOperation__Alternatives");
					put(grammarAccess.getOpUnaryAccess().getAlternatives(), "rule__OpUnary__Alternatives");
					put(grammarAccess.getXMemberFeatureCallAccess().getAlternatives_1(), "rule__XMemberFeatureCall__Alternatives_1");
					put(grammarAccess.getXMemberFeatureCallAccess().getAlternatives_1_1_0_0_1(), "rule__XMemberFeatureCall__Alternatives_1_1_0_0_1");
					put(grammarAccess.getXMemberFeatureCallAccess().getAlternatives_1_1_3_1(), "rule__XMemberFeatureCall__Alternatives_1_1_3_1");
					put(grammarAccess.getXPrimaryExpressionAccess().getAlternatives(), "rule__XPrimaryExpression__Alternatives");
					put(grammarAccess.getXLiteralAccess().getAlternatives(), "rule__XLiteral__Alternatives");
					put(grammarAccess.getXExpressionInsideBlockAccess().getAlternatives(), "rule__XExpressionInsideBlock__Alternatives");
					put(grammarAccess.getXVariableDeclarationAccess().getAlternatives_1(), "rule__XVariableDeclaration__Alternatives_1");
					put(grammarAccess.getXVariableDeclarationAccess().getAlternatives_2(), "rule__XVariableDeclaration__Alternatives_2");
					put(grammarAccess.getXFeatureCallAccess().getAlternatives_4_1(), "rule__XFeatureCall__Alternatives_4_1");
					put(grammarAccess.getIdOrSuperAccess().getAlternatives(), "rule__IdOrSuper__Alternatives");
					put(grammarAccess.getXConstructorCallAccess().getAlternatives_5(), "rule__XConstructorCall__Alternatives_5");
					put(grammarAccess.getXBooleanLiteralAccess().getAlternatives_1(), "rule__XBooleanLiteral__Alternatives_1");
					put(grammarAccess.getXTryCatchFinallyExpressionAccess().getAlternatives_3(), "rule__XTryCatchFinallyExpression__Alternatives_3");
					put(grammarAccess.getJvmTypeReferenceAccess().getAlternatives(), "rule__JvmTypeReference__Alternatives");
					put(grammarAccess.getJvmArgumentTypeReferenceAccess().getAlternatives(), "rule__JvmArgumentTypeReference__Alternatives");
					put(grammarAccess.getJvmWildcardTypeReferenceAccess().getAlternatives_2(), "rule__JvmWildcardTypeReference__Alternatives_2");
					put(grammarAccess.getJvmTypeParameterAccess().getAlternatives_1(), "rule__JvmTypeParameter__Alternatives_1");
					put(grammarAccess.getVirtualityAccess().getAlternatives(), "rule__Virtuality__Alternatives");
					put(grammarAccess.getVisibilityAccess().getAlternatives(), "rule__Visibility__Alternatives");
					put(grammarAccess.getOwnerAccess().getAlternatives(), "rule__Owner__Alternatives");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getQtNamespaceAccess().getGroup(), "rule__QtNamespace__Group__0");
					put(grammarAccess.getQtClassAccess().getGroup(), "rule__QtClass__Group__0");
					put(grammarAccess.getQtClassAccess().getGroup_2(), "rule__QtClass__Group_2__0");
					put(grammarAccess.getQtClassAccess().getGroup_2_2(), "rule__QtClass__Group_2_2__0");
					put(grammarAccess.getQtClassAccess().getGroup_3(), "rule__QtClass__Group_3__0");
					put(grammarAccess.getQtClassAccess().getGroup_3_2(), "rule__QtClass__Group_3_2__0");
					put(grammarAccess.getQtTypeDefAccess().getGroup(), "rule__QtTypeDef__Group__0");
					put(grammarAccess.getQtConstructorAccess().getGroup(), "rule__QtConstructor__Group__0");
					put(grammarAccess.getQtConstructorAccess().getGroup_3(), "rule__QtConstructor__Group_3__0");
					put(grammarAccess.getQtConstructorAccess().getGroup_3_1(), "rule__QtConstructor__Group_3_1__0");
					put(grammarAccess.getQtPropertyAccess().getGroup(), "rule__QtProperty__Group__0");
					put(grammarAccess.getQtEnumAccess().getGroup(), "rule__QtEnum__Group__0");
					put(grammarAccess.getQtFlagsAccess().getGroup(), "rule__QtFlags__Group__0");
					put(grammarAccess.getQtEnumValueAccess().getGroup(), "rule__QtEnumValue__Group__0");
					put(grammarAccess.getQtEnumValueMaskAccess().getGroup(), "rule__QtEnumValueMask__Group__0");
					put(grammarAccess.getQtEnumValueMaskAccess().getGroup_1(), "rule__QtEnumValueMask__Group_1__0");
					put(grammarAccess.getQtBuitinTypeAccess().getGroup(), "rule__QtBuitinType__Group__0");
					put(grammarAccess.getQtFunctionAccess().getGroup(), "rule__QtFunction__Group__0");
					put(grammarAccess.getQtFunctionAccess().getGroup_7(), "rule__QtFunction__Group_7__0");
					put(grammarAccess.getQtFunctionAccess().getGroup_7_1(), "rule__QtFunction__Group_7_1__0");
					put(grammarAccess.getQtValueAccess().getGroup(), "rule__QtValue__Group__0");
					put(grammarAccess.getQtTypeRefAccess().getGroup(), "rule__QtTypeRef__Group__0");
					put(grammarAccess.getQtTypeRefAccess().getGroup_1(), "rule__QtTypeRef__Group_1__0");
					put(grammarAccess.getQtTypeRefAccess().getGroup_1_2(), "rule__QtTypeRef__Group_1_2__0");
					put(grammarAccess.getQtClassTypeRefAccess().getGroup(), "rule__QtClassTypeRef__Group__0");
					put(grammarAccess.getQtClassTypeRefAccess().getGroup_1(), "rule__QtClassTypeRef__Group_1__0");
					put(grammarAccess.getQtClassTypeRefAccess().getGroup_1_2(), "rule__QtClassTypeRef__Group_1_2__0");
					put(grammarAccess.getQtParameterAccess().getGroup(), "rule__QtParameter__Group__0");
					put(grammarAccess.getQtParameterAccess().getGroup_1(), "rule__QtParameter__Group_1__0");
					put(grammarAccess.getQtReturnValueAccess().getGroup(), "rule__QtReturnValue__Group__0");
					put(grammarAccess.getQtSignalAccess().getGroup(), "rule__QtSignal__Group__0");
					put(grammarAccess.getQtSignalAccess().getGroup_3(), "rule__QtSignal__Group_3__0");
					put(grammarAccess.getQtSignalAccess().getGroup_3_1(), "rule__QtSignal__Group_3_1__0");
					put(grammarAccess.getQtSlotAccess().getGroup(), "rule__QtSlot__Group__0");
					put(grammarAccess.getQtSlotAccess().getGroup_3(), "rule__QtSlot__Group_3__0");
					put(grammarAccess.getQtSlotAccess().getGroup_3_1(), "rule__QtSlot__Group_3_1__0");
					put(grammarAccess.getXAssignmentAccess().getGroup_0(), "rule__XAssignment__Group_0__0");
					put(grammarAccess.getXAssignmentAccess().getGroup_1(), "rule__XAssignment__Group_1__0");
					put(grammarAccess.getXAssignmentAccess().getGroup_1_1(), "rule__XAssignment__Group_1_1__0");
					put(grammarAccess.getXAssignmentAccess().getGroup_1_1_0(), "rule__XAssignment__Group_1_1_0__0");
					put(grammarAccess.getXAssignmentAccess().getGroup_1_1_0_0(), "rule__XAssignment__Group_1_1_0_0__0");
					put(grammarAccess.getXOrExpressionAccess().getGroup(), "rule__XOrExpression__Group__0");
					put(grammarAccess.getXOrExpressionAccess().getGroup_1(), "rule__XOrExpression__Group_1__0");
					put(grammarAccess.getXOrExpressionAccess().getGroup_1_0(), "rule__XOrExpression__Group_1_0__0");
					put(grammarAccess.getXOrExpressionAccess().getGroup_1_0_0(), "rule__XOrExpression__Group_1_0_0__0");
					put(grammarAccess.getXAndExpressionAccess().getGroup(), "rule__XAndExpression__Group__0");
					put(grammarAccess.getXAndExpressionAccess().getGroup_1(), "rule__XAndExpression__Group_1__0");
					put(grammarAccess.getXAndExpressionAccess().getGroup_1_0(), "rule__XAndExpression__Group_1_0__0");
					put(grammarAccess.getXAndExpressionAccess().getGroup_1_0_0(), "rule__XAndExpression__Group_1_0_0__0");
					put(grammarAccess.getXEqualityExpressionAccess().getGroup(), "rule__XEqualityExpression__Group__0");
					put(grammarAccess.getXEqualityExpressionAccess().getGroup_1(), "rule__XEqualityExpression__Group_1__0");
					put(grammarAccess.getXEqualityExpressionAccess().getGroup_1_0(), "rule__XEqualityExpression__Group_1_0__0");
					put(grammarAccess.getXEqualityExpressionAccess().getGroup_1_0_0(), "rule__XEqualityExpression__Group_1_0_0__0");
					put(grammarAccess.getXRelationalExpressionAccess().getGroup(), "rule__XRelationalExpression__Group__0");
					put(grammarAccess.getXRelationalExpressionAccess().getGroup_1_0(), "rule__XRelationalExpression__Group_1_0__0");
					put(grammarAccess.getXRelationalExpressionAccess().getGroup_1_0_0(), "rule__XRelationalExpression__Group_1_0_0__0");
					put(grammarAccess.getXRelationalExpressionAccess().getGroup_1_0_0_0(), "rule__XRelationalExpression__Group_1_0_0_0__0");
					put(grammarAccess.getXRelationalExpressionAccess().getGroup_1_1(), "rule__XRelationalExpression__Group_1_1__0");
					put(grammarAccess.getXRelationalExpressionAccess().getGroup_1_1_0(), "rule__XRelationalExpression__Group_1_1_0__0");
					put(grammarAccess.getXRelationalExpressionAccess().getGroup_1_1_0_0(), "rule__XRelationalExpression__Group_1_1_0_0__0");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getGroup(), "rule__XOtherOperatorExpression__Group__0");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getGroup_1(), "rule__XOtherOperatorExpression__Group_1__0");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getGroup_1_0(), "rule__XOtherOperatorExpression__Group_1_0__0");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getGroup_1_0_0(), "rule__XOtherOperatorExpression__Group_1_0_0__0");
					put(grammarAccess.getXAdditiveExpressionAccess().getGroup(), "rule__XAdditiveExpression__Group__0");
					put(grammarAccess.getXAdditiveExpressionAccess().getGroup_1(), "rule__XAdditiveExpression__Group_1__0");
					put(grammarAccess.getXAdditiveExpressionAccess().getGroup_1_0(), "rule__XAdditiveExpression__Group_1_0__0");
					put(grammarAccess.getXAdditiveExpressionAccess().getGroup_1_0_0(), "rule__XAdditiveExpression__Group_1_0_0__0");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getGroup(), "rule__XMultiplicativeExpression__Group__0");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getGroup_1(), "rule__XMultiplicativeExpression__Group_1__0");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getGroup_1_0(), "rule__XMultiplicativeExpression__Group_1_0__0");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getGroup_1_0_0(), "rule__XMultiplicativeExpression__Group_1_0_0__0");
					put(grammarAccess.getXUnaryOperationAccess().getGroup_0(), "rule__XUnaryOperation__Group_0__0");
					put(grammarAccess.getXCastedExpressionAccess().getGroup(), "rule__XCastedExpression__Group__0");
					put(grammarAccess.getXCastedExpressionAccess().getGroup_1(), "rule__XCastedExpression__Group_1__0");
					put(grammarAccess.getXCastedExpressionAccess().getGroup_1_0(), "rule__XCastedExpression__Group_1_0__0");
					put(grammarAccess.getXCastedExpressionAccess().getGroup_1_0_0(), "rule__XCastedExpression__Group_1_0_0__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup(), "rule__XMemberFeatureCall__Group__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup_1_0(), "rule__XMemberFeatureCall__Group_1_0__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup_1_0_0(), "rule__XMemberFeatureCall__Group_1_0_0__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup_1_0_0_0(), "rule__XMemberFeatureCall__Group_1_0_0_0__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup_1_1(), "rule__XMemberFeatureCall__Group_1_1__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup_1_1_0(), "rule__XMemberFeatureCall__Group_1_1_0__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup_1_1_0_0(), "rule__XMemberFeatureCall__Group_1_1_0_0__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup_1_1_1(), "rule__XMemberFeatureCall__Group_1_1_1__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup_1_1_1_2(), "rule__XMemberFeatureCall__Group_1_1_1_2__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup_1_1_3(), "rule__XMemberFeatureCall__Group_1_1_3__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup_1_1_3_1_1(), "rule__XMemberFeatureCall__Group_1_1_3_1_1__0");
					put(grammarAccess.getXMemberFeatureCallAccess().getGroup_1_1_3_1_1_1(), "rule__XMemberFeatureCall__Group_1_1_3_1_1_1__0");
					put(grammarAccess.getXClosureAccess().getGroup(), "rule__XClosure__Group__0");
					put(grammarAccess.getXClosureAccess().getGroup_2(), "rule__XClosure__Group_2__0");
					put(grammarAccess.getXClosureAccess().getGroup_2_1(), "rule__XClosure__Group_2_1__0");
					put(grammarAccess.getXShortClosureAccess().getGroup(), "rule__XShortClosure__Group__0");
					put(grammarAccess.getXShortClosureAccess().getGroup_0(), "rule__XShortClosure__Group_0__0");
					put(grammarAccess.getXShortClosureAccess().getGroup_0_0(), "rule__XShortClosure__Group_0_0__0");
					put(grammarAccess.getXShortClosureAccess().getGroup_0_0_1(), "rule__XShortClosure__Group_0_0_1__0");
					put(grammarAccess.getXShortClosureAccess().getGroup_0_0_1_1(), "rule__XShortClosure__Group_0_0_1_1__0");
					put(grammarAccess.getXParenthesizedExpressionAccess().getGroup(), "rule__XParenthesizedExpression__Group__0");
					put(grammarAccess.getXIfExpressionAccess().getGroup(), "rule__XIfExpression__Group__0");
					put(grammarAccess.getXIfExpressionAccess().getGroup_6(), "rule__XIfExpression__Group_6__0");
					put(grammarAccess.getXSwitchExpressionAccess().getGroup(), "rule__XSwitchExpression__Group__0");
					put(grammarAccess.getXSwitchExpressionAccess().getGroup_2(), "rule__XSwitchExpression__Group_2__0");
					put(grammarAccess.getXSwitchExpressionAccess().getGroup_6(), "rule__XSwitchExpression__Group_6__0");
					put(grammarAccess.getXCasePartAccess().getGroup(), "rule__XCasePart__Group__0");
					put(grammarAccess.getXCasePartAccess().getGroup_1(), "rule__XCasePart__Group_1__0");
					put(grammarAccess.getXForLoopExpressionAccess().getGroup(), "rule__XForLoopExpression__Group__0");
					put(grammarAccess.getXWhileExpressionAccess().getGroup(), "rule__XWhileExpression__Group__0");
					put(grammarAccess.getXDoWhileExpressionAccess().getGroup(), "rule__XDoWhileExpression__Group__0");
					put(grammarAccess.getXBlockExpressionAccess().getGroup(), "rule__XBlockExpression__Group__0");
					put(grammarAccess.getXBlockExpressionAccess().getGroup_2(), "rule__XBlockExpression__Group_2__0");
					put(grammarAccess.getXVariableDeclarationAccess().getGroup(), "rule__XVariableDeclaration__Group__0");
					put(grammarAccess.getXVariableDeclarationAccess().getGroup_2_0(), "rule__XVariableDeclaration__Group_2_0__0");
					put(grammarAccess.getXVariableDeclarationAccess().getGroup_2_0_0(), "rule__XVariableDeclaration__Group_2_0_0__0");
					put(grammarAccess.getXVariableDeclarationAccess().getGroup_3(), "rule__XVariableDeclaration__Group_3__0");
					put(grammarAccess.getJvmFormalParameterAccess().getGroup(), "rule__JvmFormalParameter__Group__0");
					put(grammarAccess.getXFeatureCallAccess().getGroup(), "rule__XFeatureCall__Group__0");
					put(grammarAccess.getXFeatureCallAccess().getGroup_2(), "rule__XFeatureCall__Group_2__0");
					put(grammarAccess.getXFeatureCallAccess().getGroup_2_2(), "rule__XFeatureCall__Group_2_2__0");
					put(grammarAccess.getXFeatureCallAccess().getGroup_4(), "rule__XFeatureCall__Group_4__0");
					put(grammarAccess.getXFeatureCallAccess().getGroup_4_1_1(), "rule__XFeatureCall__Group_4_1_1__0");
					put(grammarAccess.getXFeatureCallAccess().getGroup_4_1_1_1(), "rule__XFeatureCall__Group_4_1_1_1__0");
					put(grammarAccess.getStaticQualifierAccess().getGroup(), "rule__StaticQualifier__Group__0");
					put(grammarAccess.getXConstructorCallAccess().getGroup(), "rule__XConstructorCall__Group__0");
					put(grammarAccess.getXConstructorCallAccess().getGroup_3(), "rule__XConstructorCall__Group_3__0");
					put(grammarAccess.getXConstructorCallAccess().getGroup_3_2(), "rule__XConstructorCall__Group_3_2__0");
					put(grammarAccess.getXConstructorCallAccess().getGroup_5_1(), "rule__XConstructorCall__Group_5_1__0");
					put(grammarAccess.getXConstructorCallAccess().getGroup_5_1_1(), "rule__XConstructorCall__Group_5_1_1__0");
					put(grammarAccess.getXBooleanLiteralAccess().getGroup(), "rule__XBooleanLiteral__Group__0");
					put(grammarAccess.getXNullLiteralAccess().getGroup(), "rule__XNullLiteral__Group__0");
					put(grammarAccess.getXIntLiteralAccess().getGroup(), "rule__XIntLiteral__Group__0");
					put(grammarAccess.getXStringLiteralAccess().getGroup(), "rule__XStringLiteral__Group__0");
					put(grammarAccess.getXTypeLiteralAccess().getGroup(), "rule__XTypeLiteral__Group__0");
					put(grammarAccess.getXThrowExpressionAccess().getGroup(), "rule__XThrowExpression__Group__0");
					put(grammarAccess.getXReturnExpressionAccess().getGroup(), "rule__XReturnExpression__Group__0");
					put(grammarAccess.getXTryCatchFinallyExpressionAccess().getGroup(), "rule__XTryCatchFinallyExpression__Group__0");
					put(grammarAccess.getXTryCatchFinallyExpressionAccess().getGroup_3_0(), "rule__XTryCatchFinallyExpression__Group_3_0__0");
					put(grammarAccess.getXTryCatchFinallyExpressionAccess().getGroup_3_0_1(), "rule__XTryCatchFinallyExpression__Group_3_0_1__0");
					put(grammarAccess.getXTryCatchFinallyExpressionAccess().getGroup_3_1(), "rule__XTryCatchFinallyExpression__Group_3_1__0");
					put(grammarAccess.getXCatchClauseAccess().getGroup(), "rule__XCatchClause__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getXFunctionTypeRefAccess().getGroup(), "rule__XFunctionTypeRef__Group__0");
					put(grammarAccess.getXFunctionTypeRefAccess().getGroup_0(), "rule__XFunctionTypeRef__Group_0__0");
					put(grammarAccess.getXFunctionTypeRefAccess().getGroup_0_2(), "rule__XFunctionTypeRef__Group_0_2__0");
					put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getGroup(), "rule__JvmParameterizedTypeReference__Group__0");
					put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getGroup_1(), "rule__JvmParameterizedTypeReference__Group_1__0");
					put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getGroup_1_2(), "rule__JvmParameterizedTypeReference__Group_1_2__0");
					put(grammarAccess.getJvmWildcardTypeReferenceAccess().getGroup(), "rule__JvmWildcardTypeReference__Group__0");
					put(grammarAccess.getJvmUpperBoundAccess().getGroup(), "rule__JvmUpperBound__Group__0");
					put(grammarAccess.getJvmUpperBoundAndedAccess().getGroup(), "rule__JvmUpperBoundAnded__Group__0");
					put(grammarAccess.getJvmLowerBoundAccess().getGroup(), "rule__JvmLowerBound__Group__0");
					put(grammarAccess.getJvmTypeParameterAccess().getGroup(), "rule__JvmTypeParameter__Group__0");
					put(grammarAccess.getJvmTypeParameterAccess().getGroup_1_0(), "rule__JvmTypeParameter__Group_1_0__0");
					put(grammarAccess.getQtIdlTypAccess().getElementAssignment(), "rule__QtIdlTyp__ElementAssignment");
					put(grammarAccess.getQtNamespaceAccess().getNameAssignment_1(), "rule__QtNamespace__NameAssignment_1");
					put(grammarAccess.getQtNamespaceAccess().getNamespacesAssignment_3_0(), "rule__QtNamespace__NamespacesAssignment_3_0");
					put(grammarAccess.getQtNamespaceAccess().getEnumsAssignment_3_1(), "rule__QtNamespace__EnumsAssignment_3_1");
					put(grammarAccess.getQtNamespaceAccess().getFlagsAssignment_3_2(), "rule__QtNamespace__FlagsAssignment_3_2");
					put(grammarAccess.getQtNamespaceAccess().getClassesAssignment_3_3(), "rule__QtNamespace__ClassesAssignment_3_3");
					put(grammarAccess.getQtNamespaceAccess().getOperationsAssignment_3_4(), "rule__QtNamespace__OperationsAssignment_3_4");
					put(grammarAccess.getQtNamespaceAccess().getTypedefAssignment_3_5(), "rule__QtNamespace__TypedefAssignment_3_5");
					put(grammarAccess.getQtClassAccess().getNameAssignment_1(), "rule__QtClass__NameAssignment_1");
					put(grammarAccess.getQtClassAccess().getTemplateTypesAssignment_2_1(), "rule__QtClass__TemplateTypesAssignment_2_1");
					put(grammarAccess.getQtClassAccess().getTemplateTypesAssignment_2_2_1(), "rule__QtClass__TemplateTypesAssignment_2_2_1");
					put(grammarAccess.getQtClassAccess().getSuperTypesAssignment_3_1(), "rule__QtClass__SuperTypesAssignment_3_1");
					put(grammarAccess.getQtClassAccess().getSuperTypesAssignment_3_2_1(), "rule__QtClass__SuperTypesAssignment_3_2_1");
					put(grammarAccess.getQtClassAccess().getEnumsAssignment_5_0(), "rule__QtClass__EnumsAssignment_5_0");
					put(grammarAccess.getQtClassAccess().getFlagsAssignment_5_1(), "rule__QtClass__FlagsAssignment_5_1");
					put(grammarAccess.getQtClassAccess().getClassesAssignment_5_2(), "rule__QtClass__ClassesAssignment_5_2");
					put(grammarAccess.getQtClassAccess().getPropertiesAssignment_5_3(), "rule__QtClass__PropertiesAssignment_5_3");
					put(grammarAccess.getQtClassAccess().getConstructorsAssignment_5_4(), "rule__QtClass__ConstructorsAssignment_5_4");
					put(grammarAccess.getQtClassAccess().getOperationsAssignment_5_5(), "rule__QtClass__OperationsAssignment_5_5");
					put(grammarAccess.getQtClassAccess().getTypedefAssignment_5_6(), "rule__QtClass__TypedefAssignment_5_6");
					put(grammarAccess.getQtTemplateParamAccess().getNameAssignment(), "rule__QtTemplateParam__NameAssignment");
					put(grammarAccess.getQtTypeDefAccess().getNameAssignment_1(), "rule__QtTypeDef__NameAssignment_1");
					put(grammarAccess.getQtTypeDefAccess().getTypeRefAssignment_3(), "rule__QtTypeDef__TypeRefAssignment_3");
					put(grammarAccess.getQtConstructorAccess().getParamsAssignment_3_0(), "rule__QtConstructor__ParamsAssignment_3_0");
					put(grammarAccess.getQtConstructorAccess().getParamsAssignment_3_1_1(), "rule__QtConstructor__ParamsAssignment_3_1_1");
					put(grammarAccess.getQtPropertyAccess().getTypeAssignment_1(), "rule__QtProperty__TypeAssignment_1");
					put(grammarAccess.getQtEnumAccess().getNameAssignment_1(), "rule__QtEnum__NameAssignment_1");
					put(grammarAccess.getQtEnumAccess().getValuesAssignment_3(), "rule__QtEnum__ValuesAssignment_3");
					put(grammarAccess.getQtFlagsAccess().getNameAssignment_1(), "rule__QtFlags__NameAssignment_1");
					put(grammarAccess.getQtFlagsAccess().getEnumerationAssignment_3(), "rule__QtFlags__EnumerationAssignment_3");
					put(grammarAccess.getQtEnumValueAccess().getNameAssignment_0(), "rule__QtEnumValue__NameAssignment_0");
					put(grammarAccess.getQtEnumValueAccess().getEnumMaskAssignment_2(), "rule__QtEnumValue__EnumMaskAssignment_2");
					put(grammarAccess.getQtEnumValueMaskAccess().getValueAssignment_0_0(), "rule__QtEnumValueMask__ValueAssignment_0_0");
					put(grammarAccess.getQtEnumValueMaskAccess().getNumericValueAssignment_0_1(), "rule__QtEnumValueMask__NumericValueAssignment_0_1");
					put(grammarAccess.getQtEnumValueMaskAccess().getValueAssignment_1_1_0(), "rule__QtEnumValueMask__ValueAssignment_1_1_0");
					put(grammarAccess.getQtEnumValueMaskAccess().getNumericValueAssignment_1_1_1(), "rule__QtEnumValueMask__NumericValueAssignment_1_1_1");
					put(grammarAccess.getQtBuitinTypeAccess().getNameAssignment_1(), "rule__QtBuitinType__NameAssignment_1");
					put(grammarAccess.getQtBuitinTypeAccess().getValueAssignment_3(), "rule__QtBuitinType__ValueAssignment_3");
					put(grammarAccess.getQtFunctionAccess().getVisibilityAssignment_0(), "rule__QtFunction__VisibilityAssignment_0");
					put(grammarAccess.getQtFunctionAccess().getConstAssignment_1(), "rule__QtFunction__ConstAssignment_1");
					put(grammarAccess.getQtFunctionAccess().getVirtualAssignment_2(), "rule__QtFunction__VirtualAssignment_2");
					put(grammarAccess.getQtFunctionAccess().getOwnerAssignment_3(), "rule__QtFunction__OwnerAssignment_3");
					put(grammarAccess.getQtFunctionAccess().getNameAssignment_5(), "rule__QtFunction__NameAssignment_5");
					put(grammarAccess.getQtFunctionAccess().getParamsAssignment_7_0(), "rule__QtFunction__ParamsAssignment_7_0");
					put(grammarAccess.getQtFunctionAccess().getParamsAssignment_7_1_1(), "rule__QtFunction__ParamsAssignment_7_1_1");
					put(grammarAccess.getQtFunctionAccess().getReturnValueAssignment_10(), "rule__QtFunction__ReturnValueAssignment_10");
					put(grammarAccess.getQtValueAccess().getConstAssignment_0(), "rule__QtValue__ConstAssignment_0");
					put(grammarAccess.getQtValueAccess().getValueTypeAssignment_1(), "rule__QtValue__ValueTypeAssignment_1");
					put(grammarAccess.getQtValueAccess().getTypeRefAssignment_2(), "rule__QtValue__TypeRefAssignment_2");
					put(grammarAccess.getQtValueAccess().getNameAssignment_3(), "rule__QtValue__NameAssignment_3");
					put(grammarAccess.getQtTypeRefAccess().getTypeAssignment_0(), "rule__QtTypeRef__TypeAssignment_0");
					put(grammarAccess.getQtTypeRefAccess().getTemplateTypesAssignment_1_1(), "rule__QtTypeRef__TemplateTypesAssignment_1_1");
					put(grammarAccess.getQtTypeRefAccess().getTemplateTypesAssignment_1_2_1(), "rule__QtTypeRef__TemplateTypesAssignment_1_2_1");
					put(grammarAccess.getQtClassTypeRefAccess().getTypeAssignment_0(), "rule__QtClassTypeRef__TypeAssignment_0");
					put(grammarAccess.getQtClassTypeRefAccess().getTemplateTypesAssignment_1_1(), "rule__QtClassTypeRef__TemplateTypesAssignment_1_1");
					put(grammarAccess.getQtClassTypeRefAccess().getTemplateTypesAssignment_1_2_1(), "rule__QtClassTypeRef__TemplateTypesAssignment_1_2_1");
					put(grammarAccess.getQtParameterAccess().getValueAssignment_0(), "rule__QtParameter__ValueAssignment_0");
					put(grammarAccess.getQtParameterAccess().getDefaultIntAssignment_1_1_0(), "rule__QtParameter__DefaultIntAssignment_1_1_0");
					put(grammarAccess.getQtParameterAccess().getDefaultEnumAssignment_1_1_1(), "rule__QtParameter__DefaultEnumAssignment_1_1_1");
					put(grammarAccess.getQtReturnValueAccess().getConstAssignment_0(), "rule__QtReturnValue__ConstAssignment_0");
					put(grammarAccess.getQtReturnValueAccess().getValueTypeAssignment_1(), "rule__QtReturnValue__ValueTypeAssignment_1");
					put(grammarAccess.getQtReturnValueAccess().getTypeRefAssignment_2(), "rule__QtReturnValue__TypeRefAssignment_2");
					put(grammarAccess.getQtSignalAccess().getNameAssignment_1(), "rule__QtSignal__NameAssignment_1");
					put(grammarAccess.getQtSignalAccess().getParamsAssignment_3_0(), "rule__QtSignal__ParamsAssignment_3_0");
					put(grammarAccess.getQtSignalAccess().getParamsAssignment_3_1_1(), "rule__QtSignal__ParamsAssignment_3_1_1");
					put(grammarAccess.getQtSignalAccess().getReturnValueAssignment_6(), "rule__QtSignal__ReturnValueAssignment_6");
					put(grammarAccess.getQtSlotAccess().getNameAssignment_1(), "rule__QtSlot__NameAssignment_1");
					put(grammarAccess.getQtSlotAccess().getParamsAssignment_3_0(), "rule__QtSlot__ParamsAssignment_3_0");
					put(grammarAccess.getQtSlotAccess().getParamsAssignment_3_1_1(), "rule__QtSlot__ParamsAssignment_3_1_1");
					put(grammarAccess.getQtSlotAccess().getReturnValueAssignment_6(), "rule__QtSlot__ReturnValueAssignment_6");
					put(grammarAccess.getXAssignmentAccess().getFeatureAssignment_0_1(), "rule__XAssignment__FeatureAssignment_0_1");
					put(grammarAccess.getXAssignmentAccess().getValueAssignment_0_3(), "rule__XAssignment__ValueAssignment_0_3");
					put(grammarAccess.getXAssignmentAccess().getFeatureAssignment_1_1_0_0_1(), "rule__XAssignment__FeatureAssignment_1_1_0_0_1");
					put(grammarAccess.getXAssignmentAccess().getRightOperandAssignment_1_1_1(), "rule__XAssignment__RightOperandAssignment_1_1_1");
					put(grammarAccess.getXOrExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XOrExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXOrExpressionAccess().getRightOperandAssignment_1_1(), "rule__XOrExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXAndExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XAndExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXAndExpressionAccess().getRightOperandAssignment_1_1(), "rule__XAndExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXEqualityExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XEqualityExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXEqualityExpressionAccess().getRightOperandAssignment_1_1(), "rule__XEqualityExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXRelationalExpressionAccess().getTypeAssignment_1_0_1(), "rule__XRelationalExpression__TypeAssignment_1_0_1");
					put(grammarAccess.getXRelationalExpressionAccess().getFeatureAssignment_1_1_0_0_1(), "rule__XRelationalExpression__FeatureAssignment_1_1_0_0_1");
					put(grammarAccess.getXRelationalExpressionAccess().getRightOperandAssignment_1_1_1(), "rule__XRelationalExpression__RightOperandAssignment_1_1_1");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XOtherOperatorExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXOtherOperatorExpressionAccess().getRightOperandAssignment_1_1(), "rule__XOtherOperatorExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXAdditiveExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XAdditiveExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXAdditiveExpressionAccess().getRightOperandAssignment_1_1(), "rule__XAdditiveExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getFeatureAssignment_1_0_0_1(), "rule__XMultiplicativeExpression__FeatureAssignment_1_0_0_1");
					put(grammarAccess.getXMultiplicativeExpressionAccess().getRightOperandAssignment_1_1(), "rule__XMultiplicativeExpression__RightOperandAssignment_1_1");
					put(grammarAccess.getXUnaryOperationAccess().getFeatureAssignment_0_1(), "rule__XUnaryOperation__FeatureAssignment_0_1");
					put(grammarAccess.getXUnaryOperationAccess().getOperandAssignment_0_2(), "rule__XUnaryOperation__OperandAssignment_0_2");
					put(grammarAccess.getXCastedExpressionAccess().getTypeAssignment_1_1(), "rule__XCastedExpression__TypeAssignment_1_1");
					put(grammarAccess.getXMemberFeatureCallAccess().getFeatureAssignment_1_0_0_0_2(), "rule__XMemberFeatureCall__FeatureAssignment_1_0_0_0_2");
					put(grammarAccess.getXMemberFeatureCallAccess().getValueAssignment_1_0_1(), "rule__XMemberFeatureCall__ValueAssignment_1_0_1");
					put(grammarAccess.getXMemberFeatureCallAccess().getNullSafeAssignment_1_1_0_0_1_1(), "rule__XMemberFeatureCall__NullSafeAssignment_1_1_0_0_1_1");
					put(grammarAccess.getXMemberFeatureCallAccess().getSpreadingAssignment_1_1_0_0_1_2(), "rule__XMemberFeatureCall__SpreadingAssignment_1_1_0_0_1_2");
					put(grammarAccess.getXMemberFeatureCallAccess().getTypeArgumentsAssignment_1_1_1_1(), "rule__XMemberFeatureCall__TypeArgumentsAssignment_1_1_1_1");
					put(grammarAccess.getXMemberFeatureCallAccess().getTypeArgumentsAssignment_1_1_1_2_1(), "rule__XMemberFeatureCall__TypeArgumentsAssignment_1_1_1_2_1");
					put(grammarAccess.getXMemberFeatureCallAccess().getFeatureAssignment_1_1_2(), "rule__XMemberFeatureCall__FeatureAssignment_1_1_2");
					put(grammarAccess.getXMemberFeatureCallAccess().getExplicitOperationCallAssignment_1_1_3_0(), "rule__XMemberFeatureCall__ExplicitOperationCallAssignment_1_1_3_0");
					put(grammarAccess.getXMemberFeatureCallAccess().getMemberCallArgumentsAssignment_1_1_3_1_0(), "rule__XMemberFeatureCall__MemberCallArgumentsAssignment_1_1_3_1_0");
					put(grammarAccess.getXMemberFeatureCallAccess().getMemberCallArgumentsAssignment_1_1_3_1_1_0(), "rule__XMemberFeatureCall__MemberCallArgumentsAssignment_1_1_3_1_1_0");
					put(grammarAccess.getXMemberFeatureCallAccess().getMemberCallArgumentsAssignment_1_1_3_1_1_1_1(), "rule__XMemberFeatureCall__MemberCallArgumentsAssignment_1_1_3_1_1_1_1");
					put(grammarAccess.getXClosureAccess().getFormalParametersAssignment_2_0(), "rule__XClosure__FormalParametersAssignment_2_0");
					put(grammarAccess.getXClosureAccess().getFormalParametersAssignment_2_1_1(), "rule__XClosure__FormalParametersAssignment_2_1_1");
					put(grammarAccess.getXClosureAccess().getExpressionAssignment_4(), "rule__XClosure__ExpressionAssignment_4");
					put(grammarAccess.getXShortClosureAccess().getFormalParametersAssignment_0_0_1_0(), "rule__XShortClosure__FormalParametersAssignment_0_0_1_0");
					put(grammarAccess.getXShortClosureAccess().getFormalParametersAssignment_0_0_1_1_1(), "rule__XShortClosure__FormalParametersAssignment_0_0_1_1_1");
					put(grammarAccess.getXShortClosureAccess().getExpressionAssignment_1(), "rule__XShortClosure__ExpressionAssignment_1");
					put(grammarAccess.getXIfExpressionAccess().getIfAssignment_3(), "rule__XIfExpression__IfAssignment_3");
					put(grammarAccess.getXIfExpressionAccess().getThenAssignment_5(), "rule__XIfExpression__ThenAssignment_5");
					put(grammarAccess.getXIfExpressionAccess().getElseAssignment_6_1(), "rule__XIfExpression__ElseAssignment_6_1");
					put(grammarAccess.getXSwitchExpressionAccess().getLocalVarNameAssignment_2_0(), "rule__XSwitchExpression__LocalVarNameAssignment_2_0");
					put(grammarAccess.getXSwitchExpressionAccess().getSwitchAssignment_3(), "rule__XSwitchExpression__SwitchAssignment_3");
					put(grammarAccess.getXSwitchExpressionAccess().getCasesAssignment_5(), "rule__XSwitchExpression__CasesAssignment_5");
					put(grammarAccess.getXSwitchExpressionAccess().getDefaultAssignment_6_2(), "rule__XSwitchExpression__DefaultAssignment_6_2");
					put(grammarAccess.getXCasePartAccess().getTypeGuardAssignment_0(), "rule__XCasePart__TypeGuardAssignment_0");
					put(grammarAccess.getXCasePartAccess().getCaseAssignment_1_1(), "rule__XCasePart__CaseAssignment_1_1");
					put(grammarAccess.getXCasePartAccess().getThenAssignment_3(), "rule__XCasePart__ThenAssignment_3");
					put(grammarAccess.getXForLoopExpressionAccess().getDeclaredParamAssignment_3(), "rule__XForLoopExpression__DeclaredParamAssignment_3");
					put(grammarAccess.getXForLoopExpressionAccess().getForExpressionAssignment_5(), "rule__XForLoopExpression__ForExpressionAssignment_5");
					put(grammarAccess.getXForLoopExpressionAccess().getEachExpressionAssignment_7(), "rule__XForLoopExpression__EachExpressionAssignment_7");
					put(grammarAccess.getXWhileExpressionAccess().getPredicateAssignment_3(), "rule__XWhileExpression__PredicateAssignment_3");
					put(grammarAccess.getXWhileExpressionAccess().getBodyAssignment_5(), "rule__XWhileExpression__BodyAssignment_5");
					put(grammarAccess.getXDoWhileExpressionAccess().getBodyAssignment_2(), "rule__XDoWhileExpression__BodyAssignment_2");
					put(grammarAccess.getXDoWhileExpressionAccess().getPredicateAssignment_5(), "rule__XDoWhileExpression__PredicateAssignment_5");
					put(grammarAccess.getXBlockExpressionAccess().getExpressionsAssignment_2_0(), "rule__XBlockExpression__ExpressionsAssignment_2_0");
					put(grammarAccess.getXVariableDeclarationAccess().getWriteableAssignment_1_0(), "rule__XVariableDeclaration__WriteableAssignment_1_0");
					put(grammarAccess.getXVariableDeclarationAccess().getTypeAssignment_2_0_0_0(), "rule__XVariableDeclaration__TypeAssignment_2_0_0_0");
					put(grammarAccess.getXVariableDeclarationAccess().getNameAssignment_2_0_0_1(), "rule__XVariableDeclaration__NameAssignment_2_0_0_1");
					put(grammarAccess.getXVariableDeclarationAccess().getNameAssignment_2_1(), "rule__XVariableDeclaration__NameAssignment_2_1");
					put(grammarAccess.getXVariableDeclarationAccess().getRightAssignment_3_1(), "rule__XVariableDeclaration__RightAssignment_3_1");
					put(grammarAccess.getJvmFormalParameterAccess().getParameterTypeAssignment_0(), "rule__JvmFormalParameter__ParameterTypeAssignment_0");
					put(grammarAccess.getJvmFormalParameterAccess().getNameAssignment_1(), "rule__JvmFormalParameter__NameAssignment_1");
					put(grammarAccess.getXFeatureCallAccess().getDeclaringTypeAssignment_1(), "rule__XFeatureCall__DeclaringTypeAssignment_1");
					put(grammarAccess.getXFeatureCallAccess().getTypeArgumentsAssignment_2_1(), "rule__XFeatureCall__TypeArgumentsAssignment_2_1");
					put(grammarAccess.getXFeatureCallAccess().getTypeArgumentsAssignment_2_2_1(), "rule__XFeatureCall__TypeArgumentsAssignment_2_2_1");
					put(grammarAccess.getXFeatureCallAccess().getFeatureAssignment_3(), "rule__XFeatureCall__FeatureAssignment_3");
					put(grammarAccess.getXFeatureCallAccess().getExplicitOperationCallAssignment_4_0(), "rule__XFeatureCall__ExplicitOperationCallAssignment_4_0");
					put(grammarAccess.getXFeatureCallAccess().getFeatureCallArgumentsAssignment_4_1_0(), "rule__XFeatureCall__FeatureCallArgumentsAssignment_4_1_0");
					put(grammarAccess.getXFeatureCallAccess().getFeatureCallArgumentsAssignment_4_1_1_0(), "rule__XFeatureCall__FeatureCallArgumentsAssignment_4_1_1_0");
					put(grammarAccess.getXFeatureCallAccess().getFeatureCallArgumentsAssignment_4_1_1_1_1(), "rule__XFeatureCall__FeatureCallArgumentsAssignment_4_1_1_1_1");
					put(grammarAccess.getXConstructorCallAccess().getConstructorAssignment_2(), "rule__XConstructorCall__ConstructorAssignment_2");
					put(grammarAccess.getXConstructorCallAccess().getTypeArgumentsAssignment_3_1(), "rule__XConstructorCall__TypeArgumentsAssignment_3_1");
					put(grammarAccess.getXConstructorCallAccess().getTypeArgumentsAssignment_3_2_1(), "rule__XConstructorCall__TypeArgumentsAssignment_3_2_1");
					put(grammarAccess.getXConstructorCallAccess().getArgumentsAssignment_5_0(), "rule__XConstructorCall__ArgumentsAssignment_5_0");
					put(grammarAccess.getXConstructorCallAccess().getArgumentsAssignment_5_1_0(), "rule__XConstructorCall__ArgumentsAssignment_5_1_0");
					put(grammarAccess.getXConstructorCallAccess().getArgumentsAssignment_5_1_1_1(), "rule__XConstructorCall__ArgumentsAssignment_5_1_1_1");
					put(grammarAccess.getXBooleanLiteralAccess().getIsTrueAssignment_1_1(), "rule__XBooleanLiteral__IsTrueAssignment_1_1");
					put(grammarAccess.getXIntLiteralAccess().getValueAssignment_1(), "rule__XIntLiteral__ValueAssignment_1");
					put(grammarAccess.getXStringLiteralAccess().getValueAssignment_1(), "rule__XStringLiteral__ValueAssignment_1");
					put(grammarAccess.getXTypeLiteralAccess().getTypeAssignment_3(), "rule__XTypeLiteral__TypeAssignment_3");
					put(grammarAccess.getXThrowExpressionAccess().getExpressionAssignment_2(), "rule__XThrowExpression__ExpressionAssignment_2");
					put(grammarAccess.getXReturnExpressionAccess().getExpressionAssignment_2(), "rule__XReturnExpression__ExpressionAssignment_2");
					put(grammarAccess.getXTryCatchFinallyExpressionAccess().getExpressionAssignment_2(), "rule__XTryCatchFinallyExpression__ExpressionAssignment_2");
					put(grammarAccess.getXTryCatchFinallyExpressionAccess().getCatchClausesAssignment_3_0_0(), "rule__XTryCatchFinallyExpression__CatchClausesAssignment_3_0_0");
					put(grammarAccess.getXTryCatchFinallyExpressionAccess().getFinallyExpressionAssignment_3_0_1_1(), "rule__XTryCatchFinallyExpression__FinallyExpressionAssignment_3_0_1_1");
					put(grammarAccess.getXTryCatchFinallyExpressionAccess().getFinallyExpressionAssignment_3_1_1(), "rule__XTryCatchFinallyExpression__FinallyExpressionAssignment_3_1_1");
					put(grammarAccess.getXCatchClauseAccess().getDeclaredParamAssignment_2(), "rule__XCatchClause__DeclaredParamAssignment_2");
					put(grammarAccess.getXCatchClauseAccess().getExpressionAssignment_4(), "rule__XCatchClause__ExpressionAssignment_4");
					put(grammarAccess.getXFunctionTypeRefAccess().getParamTypesAssignment_0_1(), "rule__XFunctionTypeRef__ParamTypesAssignment_0_1");
					put(grammarAccess.getXFunctionTypeRefAccess().getParamTypesAssignment_0_2_1(), "rule__XFunctionTypeRef__ParamTypesAssignment_0_2_1");
					put(grammarAccess.getXFunctionTypeRefAccess().getReturnTypeAssignment_2(), "rule__XFunctionTypeRef__ReturnTypeAssignment_2");
					put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getTypeAssignment_0(), "rule__JvmParameterizedTypeReference__TypeAssignment_0");
					put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getArgumentsAssignment_1_1(), "rule__JvmParameterizedTypeReference__ArgumentsAssignment_1_1");
					put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getArgumentsAssignment_1_2_1(), "rule__JvmParameterizedTypeReference__ArgumentsAssignment_1_2_1");
					put(grammarAccess.getJvmWildcardTypeReferenceAccess().getConstraintsAssignment_2_0(), "rule__JvmWildcardTypeReference__ConstraintsAssignment_2_0");
					put(grammarAccess.getJvmWildcardTypeReferenceAccess().getConstraintsAssignment_2_1(), "rule__JvmWildcardTypeReference__ConstraintsAssignment_2_1");
					put(grammarAccess.getJvmUpperBoundAccess().getTypeReferenceAssignment_1(), "rule__JvmUpperBound__TypeReferenceAssignment_1");
					put(grammarAccess.getJvmUpperBoundAndedAccess().getTypeReferenceAssignment_1(), "rule__JvmUpperBoundAnded__TypeReferenceAssignment_1");
					put(grammarAccess.getJvmLowerBoundAccess().getTypeReferenceAssignment_1(), "rule__JvmLowerBound__TypeReferenceAssignment_1");
					put(grammarAccess.getJvmTypeParameterAccess().getNameAssignment_0(), "rule__JvmTypeParameter__NameAssignment_0");
					put(grammarAccess.getJvmTypeParameterAccess().getConstraintsAssignment_1_0_0(), "rule__JvmTypeParameter__ConstraintsAssignment_1_0_0");
					put(grammarAccess.getJvmTypeParameterAccess().getConstraintsAssignment_1_0_1(), "rule__JvmTypeParameter__ConstraintsAssignment_1_0_1");
					put(grammarAccess.getJvmTypeParameterAccess().getConstraintsAssignment_1_1(), "rule__JvmTypeParameter__ConstraintsAssignment_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.ufacekit.qt.idl.dsl.ui.contentassist.antlr.internal.InternalQIdlParser typedParser = (org.ufacekit.qt.idl.dsl.ui.contentassist.antlr.internal.InternalQIdlParser) parser;
			typedParser.entryRuleQtIdlTyp();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public QIdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QIdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
