/*
 * generated by Xtext
 */
package org.ufacekit.qt.idl.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QIdlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.ufacekit.qt.idl.dsl.ui.internal.QIdlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.ufacekit.qt.idl.dsl.ui.internal.QIdlActivator.getInstance().getInjector("org.ufacekit.qt.idl.dsl.QIdl");
	}
	
}
